server: 
  port: 80
  servlet:
    context-path: /app
    
spring:
  datasource:
    initialization-mode: NEVER
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
    url: jdbc:mysql://192.168.1.122:3306/?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: zaq1XSW2
        
  
    
info: 
  app.name: ${spring.application.name}
  company.name: july-company
  build.artifactId: 33
  build.version: 1.1   

#logging:
#  file: app/app-dev.log
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
#  level: 
#    root: INFO
#    org.springframework.web: ERROR
#    cn.luxw.app: DEBUG
#    org.hibernate: ERROR